For chat notification
Signed-off-by: sagargurung1001@gmail.com <sagargurung1001@gmail.com>

diff --git a/.github/workflows/shared_steps.yml b/.github/workflows/shared_steps.yml
--- a/.github/workflows/shared_steps.yml
+++ b/.github/workflows/shared_steps.yml
@@ -1,33 +1,78 @@
-# name: Shared Steps
+name: Shared Steps
 
-# on:
-#   workflow_call:
-#     inputs:
-#       branch:
-#         type: string
+on:
+  workflow_call:
+    inputs:
+      branch:
+        type: string
 
-# jobs:
-#   build:
-#     runs-on: ubuntu-latest
+  workflow_run:
+    workflows: ["Build and Test"]
+    types:
+      - completed
 
-#     steps:
-#       - name: checkout
-#         uses: actions/checkout@v2
-#         with:
-#           ref: ${{ inputs.branch }}
+jobs:
+  unit-test:
+    runs-on: ubuntu-latest
 
-#       - name: Get branch name
-#         run: |
-#           echo "Branch name from trigger: ${{ inputs.branch }}"
+    steps:
+      - name: checkout
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ inputs.branch }}
 
-#       - name: Install node required
-#         uses: actions/setup-node@v3
-#         with:
-#           node-version: 16.x
+      - name: Get branch name
+        run: |
+          echo "Branch name from trigger: ${{ inputs.branch }}"
 
-#       - name: Install dependencies
-#         run: npm ci
+      - name: Install node required
+        uses: actions/setup-node@v3
+        with:
+          node-version: 16.x
 
-#       - name: run hello.js
-#         run: |
-#           node ./hello.js
+      - name: Install dependencies
+        run: npm ci
+
+      - name: run hello.js
+        run: |
+          node ./hello.js
+
+  api-test:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: checkout
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ inputs.branch }}
+
+      - name: Get branch name
+        run: |
+          echo "Branch name from trigger: ${{ inputs.branch }}"
+
+      - name: Install node required
+        uses: actions/setup-node@v3
+        with:
+          node-version: 16.x
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: run hello.js
+        run: |
+          node ./hello.js
+
+  overall-status:
+    runs-on: ubuntu-latest
+
+    needs: [unit-test, api-test] # This job depends on the success of both 'unit-test' and 'api-test'
+
+    steps:
+      - name: Check overall status
+        run: |
+          if [ "${{ job.status }}" != "success" ]; then
+            echo "One or more jobs failed!"
+            exit 1
+          else
+            echo "All jobs passed successfully."
+          fi
